name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWD: ${{secrets.DOCKER_PASSWD}}
      run:
        docker login -u $DOCKER_USER -p $DOCKER_PASSWD
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag notion-buddy
    - name: Docker push
      run: |
        docker tag notion-buddy ${{secrets.DOCKER_USER}}/notion-buddy:$(date +%s)
        docker push ${{secrets.DOCKER_USER}}/notion-buddy:$(date +%s)


